version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: stella-clip-postgres
    environment:
      POSTGRES_USER: stella
      POSTGRES_PASSWORD: stella123
      POSTGRES_DB: stella_clip
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: