export { createClient as createSupabaseClient } from '../lib/supabase/client'
export { createClient as createSupabaseServerClient } from '../lib/supabase/server'
export { prisma } from '../lib/prisma'
export { AuthService } from '../lib/auth'
export { NetworkService, networkService, createNetworkService } from './networkService'
export type { NetworkConfig, RequestOptions, ApiResponse, ApiError } from './networkService'